version: '3'
services:
  postgres:
    image: postgres:16.4-alpine3.20
    container_name: go_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - go_network

volumes:
  postgres_data:

networks:
  go_network: