// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID      int32       `json:"id"`
	Name    pgtype.Text `json:"name"`
	Address pgtype.Text `json:"address"`
}

type User struct {
	ID        int32       `json:"id"`
	Name      pgtype.Text `json:"name"`
	Email     pgtype.Text `json:"email"`
	CompanyID pgtype.Int4 `json:"company_id"`
}
